### ISSUE TITLE
Multiple Google Guava Dependencies in Package (18 and 26.0-jre)

### ISSUE THREAD

**Issue by dbadami** [awslabs/amazon-kinesis-connector-flink#12]
Hi,

I'm building a JAR for a Flink application which is using the Amazon Kinesis Connector and I'm running into an issue where the connector relies on two versions of the Google Guava Core Libraries. I had to set the version for the library to be strictly 18.0 in my gradle.build file but am running into a conflict as the connector relies on two versions. The error message I'm seeing as as follows:
```
Dependency path 'com.amazonaws:router:1.0' --> 'com.google.guava:guava:{strictly 18.0}'
--
112 | Dependency path 'com.amazonaws:router:1.0' --> 'software.amazon.kinesis:amazon-kinesis-connector-flink:2.0.0' --> 'com.google.guava:guava:18.0'
113 | Dependency path 'com.amazonaws:router:1.0' --> 'software.amazon.kinesis:amazon-kinesis-connector-flink:2.0.0' --> 'com.amazonaws:amazon-kinesis-producer:0.14.0' --> 'com.google.guava:guava:18.0'
114 | Dependency path 'com.amazonaws:router:1.0' --> 'software.amazon.kinesis:amazon-kinesis-connector-flink:2.0.0' --> 'com.amazonaws:amazon-kinesis-client:1.14.0' --> 'com.google.guava:guava:26.0-jre'
```

It's because the FlinkKinesisProducer is using a deprecated call [`Futures.addCallback`](https://github.com/awslabs/amazon-kinesis-connector-flink/blob/f6fb8540f6f71bfdce2e43b3b3e79123c1d19c8b/src/main/java/software/amazon/kinesis/connectors/flink/FlinkKinesisProducer.java#L304). The package also depends on 26.0-jre but this Futures method is not present in this package version.

Couple of things I tried:
- Not declaring the Guava dependency and letting it be auto-resolved led to a failure because it was pulling in 26.0-jre+ 
- I technically only need this connector for the consumer so I had used Amazon's fork for the consumer, and the mainline connector for the producer which didn't work either (not sure if someone else has tried it)
- Using 26.0-jre; the build succeeded but the actual call to the FlinkKinesisProducer failed.

I'm looking for guidance on how to proceed and ask if there are any plans of consolidating the guava dependencies that are used in the package.

**Comment by dannycranmer** [comment]
Hey,

Yes we saw an issue with this before. For this particular issue we only required one version on Guava on the classpath, so like you managed to solve it as we were not required to use the producer:
- https://issues.apache.org/jira/browse/FLINK-20350

This problem arises because Guava is not shaded and relocated like the other dependencies. If I remember correctly, there are certain Exceptions that are bubbled to the client application and shading could cause issues. There is a version of the connector that does shade ALL the dependencies. As far as I am aware this connector is compatible with Flink 1.11, so you could use this instead:
- https://mvnrepository.com/artifact/org.apache.flink/flink-sql-connector-kinesis_2.12/1.12.1
- https://github.com/apache/flink/blob/master/flink-connectors/flink-sql-connector-kinesis/pom.xml#L73

KPL has upgraded Guava to `26.0-jre`, I will take a look at updating KPL to latest in the connector:
- https://github.com/awslabs/amazon-kinesis-producer/blob/master/CHANGELOG.md#0142

**Comment by dbadami** [comment]
Hey Danny, thanks for your response. I'm using the Flink DataStream API so I won't be able to use the sql connector (at least I don't think so from my initial reading of the documentation). Thanks for looking into updating KPL -- do you have a rough idea as to when an update version would be available?

**Comment by dbadami** [comment]
I tried using the SQL connector as suggested and ran into the follow error when starting the Flink application:
```
2021-01-25 12:48:36
java.lang.NoClassDefFoundError: org/apache/flink/api/common/serialization/RuntimeContextInitializationContextAdapters
	at org.apache.flink.streaming.connectors.kinesis.FlinkKinesisProducer.open(FlinkKinesisProducer.java:237)
	at org.apache.flink.api.common.functions.util.FunctionUtils.openFunction(FunctionUtils.java:36)
	at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.open(AbstractUdfStreamOperator.java:102)
	at org.apache.flink.streaming.api.operators.StreamSink.open(StreamSink.java:48)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.initializeStateAndOpenOperators(OperatorChain.java:291)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.lambda$beforeInvoke$0(StreamTask.java:474)
	at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$1.runThrowing(StreamTaskActionExecutor.java:47)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.beforeInvoke(StreamTask.java:470)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:529)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:724)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:549)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
The SQL connector is not compatible with Flink 1.11  because RuntimeContextInitializationContextAdapters is present in  [Flink 1.12](https://ci.apache.org/projects/flink/flink-docs-release-1.12/api/java/org/apache/flink/api/common/serialization/package-summary.html) and not in [Flink 11.](https://ci.apache.org/projects/flink/flink-docs-release-1.11/api/java/org/apache/flink/api/common/serialization/package-summary.html). I'll resort to building the connector from source after upgrading KPL to 0.14.2.

**Comment by dannycranmer** [comment]
As discussed offline, this issue is a non-issue. There would be a problem if you genuinely need to use Guava 18 and 26 concurrently. However the conflict you were seeing comes from the transient dependency of KCL (Guava 26-jre). This is not actually used by the connector, and maven usually omits for 18. It seems you had a strange Gradle build problem, which has been resolved.
