### ISSUE TITLE
Is there any difference

### ISSUE THREAD

**Issue by Missshao** [awslabs/amazon-kinesis-connector-flink#33]
is there any difference between this connector with this ?
https://ci.apache.org/projects/flink/flink-docs-master/docs/connectors/datastream/kinesis/

**Comment by dannycranmer** [comment]
The difference between this library and the Apache Flink Kinesis connector, is that we have backported some features for earlier versions of Apache Flink, in order to allow customers to leverage these features with Kinesis Data Analytics:

| Feature | Flink Version |AWS Kinesis Connector | Apache Flink Kinesis connector |
| ------- | ------------ | ----------------------- | ------------------------------- |
| EFO (Enhanced Fan-Out) | 1.8 | Supported | Not supported |
| EFO (Enhanced Fan-Out) | 1.11 | Supported | Not supported |
| EFO (Enhanced Fan-Out) | 1.12 | N/A | Supported |
| EFO (Enhanced Fan-Out) | 1.13 | N/A | Supported |
| Table API | 1.8 | Not Supported | Not supported |
| Table API | 1.11 | Supported | Not supported |
| Table API | 1.12 | N/A | Supported |
| Table API | 1.13 | N/A | Supported |

In terms of bug fix parity, we try our best to port bug fixes across all versions of Flink. 

You only need to use this connector if you want to use EFO or Table API, otherwise you can use the Apache connector.

**Comment by dannycranmer** [comment]
Closing due to staleness, please reopen if needed
